version: '3.10'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 LiveStreaming.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"