version: '3.9'

services:
  redis:
    image: redis
    command:
      - redis-server
    ports:
      - "6378:6378"
  websocket_channels:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 LiveStreaming.asgi:application
    volumes:
      - .:/app
    ports:
      - "80:8000"
    links:
      - redis
