version: '3.10'

services:
  live_streaming:
    build: .
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8008'
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
    ports:
      - "5011:8008"

